---
# COLLECT USER vCENTER SETTINGS
# TODO refactor whole playbook into role
- name: Detect vCenter user settings
  hosts: psrunner
  username: "{{ svc_acct }}"
  password: "{{ svc_acct_pass }}"
  gather_facts: no
  tasks:
    - name: collect vCenter user info
      win_shell: C:\ansible\CollectvCenterUserInfo.ps1 -SamAccountName {{tower_user_name}} -VCenterName {{awxui_VCenterName}}
      args:
        executable: pwsh
      register: ps_result

    - name: Parse ps_result
      set_fact:
        vc_user_info: "{{ ps_result.stdout | from_json }}"

    - name: print parsed user info
      debug:
        msg: ps_result[10]

    #- name: Check if user datastore usage is below specified treshold
    #  assert:
    #    that:
    #      "{{vc_user_info.ConsumedSpaceTresholdGBReached}} == false "
    #    fail_msg: "Datastore usage limit reached! The job will fail now"

- name: Deploy win vm ps way
  hosts: "colsupans-ctl.ssa.veeam.local"
  remote_user: ansible
  gather_facts: no
  #become: yes
  vars_files:
    - vars.yml
    
  tasks:

    - name: Set the variables for deploying the VM
      set_fact:
        vcenter_username: "{{ hostvars['localhost']['tower_user_name'] }}@{{ domain_name }}"

    - name: Set vm_folder variable
      set_fact:
        vm_folder: "Private VMs/{{ hostvars['localhost']['tower_user_name'] | regex_replace('\\.', ' ') | title }}"
      
    - name: Deploy win vm ps way
      delegate_to: "colsupans-ctl.ssa.veeam.local"
      #deploy_vmw_win_vm_ps:
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ svc_acct }}"
        password: "{{ svc_acct_pass }}"
        validate_certs: false
        folder: "{{ vm_folder }}"
        resource_pool: "{{ resource_pool }}"
        datastore: SSA-COLSTG-DS00
        cluster: "{{ vcenter_cluster }}"
        datacenter: "{{ vcenter_datacenter }}"
        name: "{{ awxui_vm_name }}"
        template: "{{ awxui_vm_template }}"
        hardware:
          memory_mb: "{{ awxui_memory_mb }}"
          num_cpus: "{{ awxui_num_cpu_cores_per_socket }}"
        networks:
          - name: "{{ vcenter_vdpg }}"
        state: powered-on
        #join_ssa: "{{ awxui_join_ssa }}"
        #remove_from_ssa: "{{ awxui_remove_from_ssa | default(omit) }}"
        customization:
           orgname: COL Support Lab           
           joindomain: "{{ domain_name }}"
           domainadmin: "{{ ansible_user }}"
           domainadminpassword: "{{ ansible_password }}"
           existing_vm: false
           password: "{{ vm_administrator_password }}"
           timezone: 35

    - name: explicitely set creds
      set_fact:
        vc_username_e: "{{ ansible_user }}"
        vc_password_e: "{{ ansible_password }}"
      no_log: True
